language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
env:
  global:
    secure: bJVw2AK1useeUy2YF5eyZqak53b1g5hbSa4uUwdP355xIbaJMMk1HCOEr+FMsYBVfYEI8FLnfdIA24bum+9A3xas6RLC/UJUlbkyhNrA2EZDtbS3dHsWxGHaGJ6r0voTsmUIJyCYVCdKQaD9mZ8JDvc5MNUYK0ulbRcnn/0bv+A=
before_install:
- wget http://download-aws.ej-technologies.com/install4j/install4j_linux_5_1_15.deb
- sudo dpkg -i install4j_linux_5_1_15.deb
- /opt/install4j5/bin/install4jc -L $INSTALL4J_LICENSE_KEY
after_success:
- mvn package
- /opt/install4j5/bin/install4jc -r `date +"%Y%m%d%H%M%S"` -d installers OpenPnP.install4j
